name: Deploy at Itch.io

env:
  itchio_project: rqgodoy/escuridao-e-solidao
  itchio_channel: windows

on:
  #  pull_request:
  #    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneLinux64

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        uses: webbertakken/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2019.4.25f1
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.targetPlatform }}
          path: build
